### ISSUE TITLE
how to set ‘’X-Forwarded-Proto: https in the HTTP headers"

### ISSUE THREAD

**Issue by heqiangkkk** [klausmeyer/docker-registry-browser#10]
i don't know how to revamp this，when i delete ，it give me a information like this，“We're sorry, but something went wrong.”

**Comment by klausmeyer** [comment]
Can you please answer the following questions so I could help with this issue:

* Did enable the delete option in the storage section of the registry's configuration?
* Are you using any reverse proxy like apache, nginx or ha-proxy in combination with the registry-browser?

Thanks

**Comment by klausmeyer** [comment]
Did enable the delete option in the storage section of the registry's configuration?
See https://docs.docker.com/registry/configuration/#delete

Are you using any reverse proxy like apache, nginx or ha-proxy in combination with the registry-browser? If this is the case you need to add this custom header called `X-Forwarded-Proto` to the configuration. In case of nginx (just as an example):

```
server {
    listen 80;
    server_name registry.example.com;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by heqiangkkk** [comment]
thanks a lot,my config.yml configuration was wrong,should be "enabled" but i dashed off "enable"

**Comment by klausmeyer** [comment]
👍 You're welcome
