### ISSUE TITLE
Tag don't deleted

### ISSUE THREAD

**Issue by toreshonda** [klausmeyer/docker-registry-browser#114]
When I try to delete an image tag, I get an error:
[https://prnt.sc/knd2nt](url)

command to start the image:
docker run -d --name registry-browser -it -p 8000:8080 -e DOCKER_REGISTRY_URL=http://172.20.143.141:30005 -e BASIC_AUTH_USER=dockeruser -e BASIC_AUTH_PASSWORD=<password> -e ENABLE_DELETE_IMAGES=true klausmeyer/docker-registry-browser
in container logs:

> I, [2018-08-27T11:17:19.015339 #5]  INFO -- request: GET http://172.20.143.141:30005/v2/image/tags/list
D, [2018-08-27T11:17:19.015446 #5] DEBUG -- request: User-Agent: "Faraday v0.15.2"
Authorization: "Basic ZG9ja2VydXNlcjoxcWF6MndzeA=="
I, [2018-08-27T11:17:19.035075 #5]  INFO -- response: Status 200
D, [2018-08-27T11:17:19.035170 #5] DEBUG -- response: content-type: "application/json; charset=utf-8"
docker-distribution-api-version: "registry/2.0"
x-content-type-options: "nosniff"
date: "Mon, 27 Aug 2018 11:17:19 GMT"
content-length: "161"
connection: "close"
I, [2018-08-27T11:17:19.035689 #5]  INFO -- request: GET http://172.20.143.141:30005/v2/image/manifests/dev-0.2.8-ui-transaction
D, [2018-08-27T11:17:19.035745 #5] DEBUG -- request: User-Agent: "Faraday v0.15.2"
Accept: "application/vnd.docker.distribution.manifest.v2+json"
Authorization: "Basic ZG9ja2VydXNlcjoxcWF6MndzeA=="
I, [2018-08-27T11:17:19.055439 #5]  INFO -- response: Status 200
D, [2018-08-27T11:17:19.055504 #5] DEBUG -- response: content-length: "1366"
content-type: "application/vnd.docker.distribution.manifest.v2+json"
docker-content-digest: "sha256:cc9a7550b0fa3d135a6570361e478f1cfd5a9b0dd39fdd0beb96f24d58fd4ff4"
docker-distribution-api-version: "registry/2.0"
etag: "\"sha256:cc9a7550b0fa3d135a6570361e478f1cfd5a9b0dd39fdd0beb96f24d58fd4ff4\""
x-content-type-options: "nosniff"
date: "Mon, 27 Aug 2018 11:17:19 GMT"
connection: "close"
I, [2018-08-27T11:17:19.055994 #5]  INFO -- request: DELETE http://172.20.143.141:30005/v2/image/manifests/sha256:cc9a7550b0fa3d135a6570361e478f1cfd5a9b0dd39fdd0beb96f24d58fd4ff4
D, [2018-08-27T11:17:19.056039 #5] DEBUG -- request: User-Agent: "Faraday v0.15.2"
Authorization: "Basic ZG9ja2VydXNlcjoxcWF6MndzeA=="
I, [2018-08-27T11:17:19.064130 #5]  INFO -- : [fcb3c127-bde7-47cd-a039-987da757eb97] Completed 500 Internal Server Error in 50ms
F, [2018-08-27T11:17:19.064930 #5] FATAL -- : [fcb3c127-bde7-47cd-a039-987da757eb97]
F, [2018-08-27T11:17:19.064981 #5] FATAL -- : [fcb3c127-bde7-47cd-a039-987da757eb97] Faraday::ClientError (the server responded with status 405):
F, [2018-08-27T11:17:19.065005 #5] FATAL -- : [fcb3c127-bde7-47cd-a039-987da757eb97]
F, [2018-08-27T11:17:19.065027 #5] FATAL -- : [fcb3c127-bde7-47cd-a039-987da757eb97] app/models/tag.rb:37:in `delete'
[fcb3c127-bde7-47cd-a039-987da757eb97] app/controllers/tags_controller.rb:10:in `destroy'

**Comment by klausmeyer** [comment]
Looks like the docker registry connected to the browser is rejecting the delete request:

```
Faraday::ClientError (the server responded with status 405)
```

```
405 Method Not Allowed
```
🔗 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

Might be the same issue as in #15.
Did you enable deletion in the registry itself? (`REGISTRY_STORAGE_DELETE_ENABLED=true`).
