### ISSUE TITLE
Support for authentication against browser

### ISSUE THREAD

**Issue by smurfy** [klausmeyer/docker-registry-browser#135]
While i really like your browser, what i'm missing is some way to add a password (basic auth is ok) for the browser frontend. 

Sure i could put "something" in front of the browser, but this would mean, yet another docker container :)

i'm also happy with just using the regular registry user+password. So either:

1. Use the same ENV params for browser auth

or

2. "relay" 401 http response + auth headers. So i dont set the  env param for basic auth. browser tries to auth with registry, it fails with 401, so it returns the 401+authentication header back to my "web-browser". My "web-browser" handles the error (by showing a basic auth alert), on the second request my "web-browser" then sends the authentication header which then needs to be relayed to registry  I prefer this variant.

**Comment by klausmeyer** [comment]
Hey Philipp,

thanks for your feedback and the request.

I really like the idea about simply relaying the 401 response from the registry to the web-browser as you described. Will try to have a look soon.

Best, Klaus

**Comment by smurfy** [comment]
Works!

Just specified ``DOCKER_REGISTRY_URL``  and after giving correct username/password was able to browse.

THANK YOU!

**Comment by klausmeyer** [comment]
Cool :sunglasses: 

I've merged my changes so they're available in `latest` tag soon.

**Comment by tickmanpl** [comment]
Hi,

Can you add provide credentials against browser for token authentication mode ?

**Comment by klausmeyer** [comment]
That might be possible. Could you please create an own / new issue for that?

Can't promise anything but when I have some spare time I will try and have a look.
