### ISSUE TITLE
Add versioning to the project

### ISSUE THREAD

**Issue by johan-smits** [klausmeyer/docker-registry-browser#143]
:+1: for this project!

Consider adding version number to your project like [semver](https://semver.org/).
This makes it easy to track changes and updates.

**Comment by klausmeyer** [comment]
Hey Johan,

thanks for your feedback.
Good point. Will take care of that soon.

Best, Klaus

**Comment by klausmeyer** [comment]
Done. We now have a 1.0.0 release with git and docker tag:

* https://github.com/klausmeyer/docker-registry-browser/tree/v1.0.0
* https://hub.docker.com/r/klausmeyer/docker-registry-browser/tags
