### ISSUE TITLE
Self-host icons

### ISSUE THREAD

**Issue by ruffy91** [klausmeyer/docker-registry-browser#149]
Please consider hosting the images in the container itself instead on icons8.com
Serving images from an external domain poses a security and operational risk (if the external domain gets sold/hacked).

**Comment by klausmeyer** [comment]
👍 Makes sense. Will ping you once it's done.

**Comment by klausmeyer** [comment]
Done. Should be available on Docker Hub soon (`v1.0.1` or `latest` tag).

**Comment by ruffy91** [comment]
💖
That was blazing fast. 
Already running in my container.
