### ISSUE TITLE
Delete Tag button doesn't exits 

### ISSUE THREAD

**Issue by joserodriguezan** [klausmeyer/docker-registry-browser#158]
Hello,

Delete Tag button doesn't exits in version 1.0.1 (b9a6953)  Running on Ruby 2.6.1 and Rails 5.2.2

I have docker with command
`docker run --name registry-browser --rm --detach -it -p 8080:8080 -e DOCKER_REGISTRY_URL=http://192.168.2.82:5000 klausmeyer/docker-registry-browser`

**Comment by klausmeyer** [comment]
Hi @joserodriguezan,

by default the button is not enabled. You'll need to add `-e ENABLE_DELETE_IMAGES=true` to your docker run command. Also important: The delete API needs to be also enabled in the registry itself - otherwise the registry browser will throw an error on delete:

https://docs.docker.com/registry/configuration/#delete

Best, Klaus

**Comment by joserodriguezan** [comment]
Hi Claus,
I want to make this button permanent. 

Should I put this into config.yml,? If it is that case where is the file. I am looking into the container but I can't find it.

Thank you Klaus,
Jose Luis

**Comment by klausmeyer** [comment]
Not sure what you mean with `config.yml`.

The application is reading it's config from the environment variables passed to the container.
To enable the button the `ENABLE_DELETE_IMAGES` variable needs to be set to `true`.

In your example `docker run` command provided above you'd need to add it with another `-p` flag to specify the variable (like you already did with the `DOCKER_REGISTRY_URL` one).

**Comment by joserodriguezan** [comment]
Hi Klaus,

The run command I'm using is:

 # docker run --name registry-browser --rm --detach -it -p 8080:8080 -e ENABLE_DELETE_IMAGES=true -e DOCKER_REGISTRY_URL=http://192.168.2.82:5000 klausmeyer/docker-registry-browser

The button is already show. But when I try to delete a tab it shows this message: 
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Comment by klausmeyer** [comment]
Ok, that run command looks correct.
Did you enable the log deletion in the registry container (not the docker-registry-browser)?

**Comment by joserodriguezan** [comment]
This is how I ran the registry container 
# docker run -d -p 5000:5000 -v /srv/registry:/var/lib/registry  --restart always --name registry registry:latest

**Comment by klausmeyer** [comment]
Add the following flag to it: `-e REGISTRY_STORAGE_DELETE_ENABLED=true`

```diff
# docker run -d -p 5000:5000 -v /srv/registry:/var/lib/registry --restart always -e REGISTRY_STORAGE_DELETE_ENABLED=true --name registry registry:latest
```

**Comment by joserodriguezan** [comment]
Hi Klaus,

It works now. Sometimes the way to solve is to find the right person with the info. 

Thanks indeed.

**Comment by klausmeyer** [comment]
You're welcome
