### ISSUE TITLE
Not able to delete tags

### ISSUE THREAD

**Issue by joserodriguezan** [klausmeyer/docker-registry-browser#159]
Hi,

When I press Delete Tag button, tag is not deleted, instead it shows this message:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

The log says:
I, [2019-02-15T12:15:15.740060 #1]  INFO -- request: DELETE http://192.168.2.82:5000/v2/joseluis/alpine/manifests/sha256:1502b120cb36cd2b3dbd680fab778c31d535dc049b7a522fbd2f89242d4b4f29
D, [2019-02-15T12:15:15.740571 #1] DEBUG -- request: User-Agent: "Faraday v0.15.4"
I, [2019-02-15T12:15:15.745571 #1]  INFO -- : [23107d62-eb8d-4d83-aaa2-7b827156a5d2] Completed 500 Internal Server Error in 66ms
F, [2019-02-15T12:15:15.746876 #1] FATAL -- : [23107d62-eb8d-4d83-aaa2-7b827156a5d2]   
F, [2019-02-15T12:15:15.747364 #1] FATAL -- : [23107d62-eb8d-4d83-aaa2-7b827156a5d2] Faraday::ClientError (the server responded with status 405):
F, [2019-02-15T12:15:15.747672 #1] FATAL -- : [23107d62-eb8d-4d83-aaa2-7b827156a5d2]   
F, [2019-02-15T12:15:15.747986 #1] FATAL -- : [23107d62-eb8d-4d83-aaa2-7b827156a5d2] app/models/tag.rb:37:in `delete'
[23107d62-eb8d-4d83-aaa2-7b827156a5d2] app/controllers/tags_controller.rb:10:in `destroy'

Thank you,

**Comment by klausmeyer** [comment]
Just to be sure:
Did you enable the `storage.delete.enabled` option in the registry itself?
(See https://github.com/klausmeyer/docker-registry-browser/issues/158#issuecomment-463997926)

**Comment by joserodriguezan** [comment]
I am working thru this post: (See [#158 (comment)](https://github.com/klausmeyer/docker-registry-browser/issues/158#issuecomment-463997926))
