### ISSUE TITLE
Token Authentication not working

### ISSUE THREAD

**Issue by HMIDeer** [klausmeyer/docker-registry-browser#187]
I've tried to run a authenticated registry using https://github.com/cesanta/docker_auth. The login via CLI is working fine. I've configured the user by adding TOKEN_AUTH_USER and TOKEN_AUTH_PASSWORD. The request to the docker_auth server https://ip-address/auth?client_id=docker-registry-browser&offline_token=true&scope=registry%3Acatalog%3A%2A&service=Docker-registry is not possible because the request seems to be invalid for the docker_auth server (it throws an exception in the docker_auth log)

**Comment by HMIDeer** [comment]
After trying around with the configuration of the docker_auth i've found an issue there. Sorry for the inconvenience.

**Comment by klausmeyer** [comment]
👍 No worries ;)
