### ISSUE TITLE
Allow deletion of null tags

### ISSUE THREAD

**Issue by rhuanbarreto** [klausmeyer/docker-registry-browser#199]
I don't know how, but I have a null tag in my image. And using your image I can't confirm the deletion because the button don't enable when I write `null`.
Pretty obvious but need to convert the null written to text.
![Captura de Tela 2019-07-02 às 09 31 11](https://user-images.githubusercontent.com/283004/60495629-71914100-9cb1-11e9-8f91-c184f4a60c79.png)
![image](https://user-images.githubusercontent.com/283004/60495665-87066b00-9cb1-11e9-8a61-443b96fbf9ba.png)

**Comment by klausmeyer** [comment]
Thanks for reporting this issue. Indeed a very interesting case.
Will have a look.

**Comment by klausmeyer** [comment]
@rhuanbarreto I've released a new version (v1.2.1) which includes a fix for your issue.
Could you please give it a try?
