### ISSUE TITLE
Tag page works only for "latest"

### ISSUE THREAD

**Issue by amenophis** [klausmeyer/docker-registry-browser#2]
Hi,
I can't access tag detail page with url like this: /repo/xxx/yyy/tag/1.4.2, but it works for /repo/xxx/yyy/tag/latest.

Is it a known bug ?

**Comment by klausmeyer** [comment]
Not a known but since my tags don't have dots in them yet but I already know hot to fix this issue.
Thanks for reporting.

**Comment by klausmeyer** [comment]
I've pushed a fix for this issue.

**Comment by amenophis** [comment]
Works great !
Thanks !
