### ISSUE TITLE
support something?

### ISSUE THREAD

**Issue by cantgis** [klausmeyer/docker-registry-browser#221]
1. show search
2. show info of each layer or only show environment variables in the image
3. simple user and password login
4. custom mush list show this for images more
5. show info of LABEL

**Comment by klausmeyer** [comment]
Hi @cantgis,

thanks for your interest in this project 🙂

I assume the points you are listing are features you'd like to see in this application - right?

For most of them I am not sure exactly what is meant so it would be great if you could add a few more details about them.

In general this application is kept very simple and only supports stuff provided by the docker registry API itself which also is **very** limited in it's features as far as I know.

In case you're looking for a more advanced UI for the docker registry you could have a look at https://github.com/SUSE/Portus / http://port.us.org.

Best, Klaus
