### ISSUE TITLE
unable to set listening interface

### ISSUE THREAD

**Issue by hboetes** [klausmeyer/docker-registry-browser#234]
Since I want to run docker-registry-browser via nginx as a reverse proxy, I'd like to run it only 127.0.0.1 but I can't find the env variable to configure that.

How can I set that? Thanks!

**Comment by klausmeyer** [comment]
At the moment there is no such option available.

I'll have a look later and will try to provide a solution.

**Comment by klausmeyer** [comment]
I've a PR ready now that adds a config var: #235
Could you checkout that branch and give it a try before I merge it?
Basically you'd need to pass `ADDRESS=127.0.0.1` when starting the app.

**Comment by hboetes** [comment]
Yes, now it's listening on 127.0.0.1

```
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
Puma starting in single mode...
* Version 4.2.1 (ruby 2.6.5-p114), codename: Distant Airhorns
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://127.0.0.1:8080
Use Ctrl-C to stop

```

BTW, is the yarn notice important?

**Comment by klausmeyer** [comment]
Cool 😎 I think you can ignore the Yarn message for now.

**Comment by hboetes** [comment]
Thanks for the quick fixes BTW.

**Comment by klausmeyer** [comment]
You're welcome 👍
