### ISSUE TITLE
RAILS_RELATIVE_URL_ROOT=/browser doesn't work consistently

### ISSUE THREAD

**Issue by hboetes** [klausmeyer/docker-registry-browser#236]
Hi there:

I'm running with:
`RAILS_RELATIVE_URL_ROOT=/browser ENABLE_DELETE_IMAGES=true DOCKER_REGISTRY_URL=https://example.com PORT=8080 bundle exec bundle exec puma -C config/puma.rb`

And then I'm running nginx as a reverse proxy with SSL which redirects `/browser` to `docker-registry-browser`.

So if I open `https://example.com/browser` it looks OK, but if I for example click on alpine I get sent to `https://example.com/repo/alpine` which misses the /browser part. If I go to `https://example.com/browser/repo/alpine` I do get to see the right page.

Can you reproduce this error?

**Comment by klausmeyer** [comment]
I just had a look at the issue in which this feature was initially requested: #179.

Looks like back then when we tried it we did set a 2nd env setting called `SCRIPT_NAME`.
Might have missed to document that.

Can you try with it?

```
SCRIPT_NAME=/browser RAILS_RELATIVE_URL_ROOT=/browser [...] bundle exec [...]
```

**Comment by hboetes** [comment]
Great! Now it works! Thanks!
