### ISSUE TITLE
Show extra information for images

### ISSUE THREAD

**Issue by nestor-alonso** [klausmeyer/docker-registry-browser#241]
Show author and creation dates for images, like:

https://raw.githubusercontent.com/Joxit/docker-registry-ui/master/docker-registry-ui.gif

**Comment by klausmeyer** [comment]
I've just pushed a experimental tag which contains the requested feature:

```
docker pul klausmeyer/docker-registry-browser:more-tag-details
```
Would you please give it a try and tell me if it works for you?

**Comment by nestor-alonso** [comment]
This is awesome!!!!

 

Thank you so much!

 

Are you going to keep the tag, or include this feature in the mainstream?

 

Nestor

 

Sent: Thursday, November 07, 2019 at 10:23 AM

**Comment by klausmeyer** [comment]
I'll merge it into the mainstream and push a new release soon.
The tag will go away after that.

**Comment by klausmeyer** [comment]
Release `v1.3.0` tag and updated `latest` tag will be available on Docker-Hub soon.
