### ISSUE TITLE
Delete button doesn't work (not active)

### ISSUE THREAD

**Issue by zikolach** [klausmeyer/docker-registry-browser#3]
Started app in docker with all necessary parameters:

```
docker run --name registry-browser -it --rm -p 8080:8080 -e DOCKER_REGISTRY_URL=https://myserver.com-e BASIC_AUTH_USER=user -e BASIC_AUTH_PASSWORD=secret -e ENABLE_DELETE_IMAGES=true klausmeyer/docker-registry-browser
```

Delete button is inactive after entering image tag.

**Comment by klausmeyer** [comment]
Hi @zikolach,

thanks for reporting this bug.

I recently noticed as well that the delete button does not become active when you enter the tag-name. 

One quick workaround for now seems to be to reload the page when you're on the detail-page of the tag before you fill in the input-field. I might be able to fix this issue soon.

Best, Klaus

**Comment by klausmeyer** [comment]
I've now pushed a fix for the issue and will now make sure to provide a updated image on dockerhub.
