### ISSUE TITLE
Arm64 images

### ISSUE THREAD

**Issue by thejimnicholson** [klausmeyer/docker-registry-browser#300]
Not really an issue, just an FYI: I was able to build the image for arm64 from your source without modification. I built it using the docker buildx. The image is in docker hub at thejimnicholson/docker-registry-browser. I don't know if docker's github builder supports multiarch images, but it wouldn't be hard to make one using buildx that could be used on multiple platforms.

**Comment by qs5779** [comment]
Github now has support for building / pushing multi arch images with workflows. You can see a basic example here: [example](https://github.com/wtfo-guru/wtfmail/blob/master/.github/workflows/master.yml)

**Comment by klausmeyer** [comment]
As a side-effect of migrating from Docker Hub automated builds to GitHub actions today I also enabled multi-platform builds.

The `latest` tag is now available for amd64 & arm64:

![2021-09-17-160401_675x219_scrot](https://user-images.githubusercontent.com/615777/133796207-01cc9200-01d6-4fa1-906f-d1c8f732c4de.png)

Unfortunately I don't own a arm64 device (yet) so it would be great if someone else could give it a try.

**Comment by klausmeyer** [comment]
Just figured out that the Raspberry PI 3 I own is already a 64bit ARM:

```
ubuntu@ubuntu:~$ sudo docker version -f '{{.Server.Arch}}'
arm64
ubuntu@ubuntu:~$ sudo docker run -it -p 8080:8080 klausmeyer/docker-registry-browser:latest
Puma starting in single mode...
* Puma version: 5.4.0 (ruby 3.0.2-p107) ("Super Flight")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 1
* Listening on http://0.0.0.0:8080
Use Ctrl-C to stop
I, [2021-09-17T15:06:35.225178 #1]  INFO -- : [faaa6d9c-8d55-4e6d-b29d-f896cd65d123] Started GET "/" for 172.17.0.1 at 2021-09-17 15:06:35 +0000
```

:partying_face:
