### ISSUE TITLE
Subfolder deploy goes into redirect loop.

### ISSUE THREAD

**Issue by toshi-k** [klausmeyer/docker-registry-browser#303]
I'm trying subfolder deploy in accordance with README.md.

```
docker run --name registry-browser
  -p 8081:8080
  -e DOCKER_REGISTRY_URL=http://***.***.***.***:5000
  -e RAILS_RELATIVE_URL_ROOT=/registry-browser \
  -e SCRIPT_NAME=/registry-browser \
   klausmeyer/docker-registry-browser:1.3.4 
```

But, when I access on web browser (Chrome), I face redirect loop.
URL bar shows as below.
```
***.***.***.***:8081/registry-browser/repo/registry-browser/repo/registry-browser/repo/registry-browser/repo/registry-browser/repo
```

Is subfolder deploy available on v1.3.4 ? Is there any other things I have to add ?
I would appreciate if someone help me resolving this issue.

**Comment by toshi-k** [comment]
Sorry, I solved the problem by myself.
I had to access root by network routing while keeping other contents in the subfolder.

**Comment by klausmeyer** [comment]
No worries. Glad you found a solution.
