### ISSUE TITLE
Provide credentials against browser for token authentication

### ISSUE THREAD

**Issue by jkucinski** [klausmeyer/docker-registry-browser#313]
Hello,

Could you add provide credentials against browser for token authentication mode.
Authentication with auth server works on http basic auth, so I think that's possible to do.

**Comment by guikeller** [comment]
+1

**Comment by s3477631** [comment]
+1

**Comment by klausmeyer** [comment]
Hey everyone,

I managed to do the needed changes and would like invite you folks to try it out before I merge it into the main branch.

You can pull the following docker image:

```
klausmeyer/docker-registry-browser:preview-feature-313
```

Just make sure to not set the `TOKEN_AUTH_*` environment variables and the application should ask the browser to provide the username and password to obtain the token from the auth server instead.

Please let me know if any issues pop up.

Thanks, Klaus

**Comment by guikeller** [comment]
Hi @klausmeyer 

It is working great; I have just tested it.
Thank you very much for implementing this feature.

Cheers! 👍

**Comment by jkucinski** [comment]
It's working flawlessly.
Thanks for adding this feature.

**Comment by klausmeyer** [comment]
Thanks for your feedback. I've now merged the change and it will be available in `latest` tag soon.
