### ISSUE TITLE
Where to find Log-Files

### ISSUE THREAD

**Issue by Nusserdt** [klausmeyer/docker-registry-browser#338]
Hello Klaus,

I try to configure `ENABLE_DELETE_IMAGES` to delete images in my registry. When I try to delete an image, the `docker-registry-browser` give me the feedback: 

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

![image](https://user-images.githubusercontent.com/35678990/99046387-f58c5600-2592-11eb-83a0-981b94b6b1eb.png)

So where can I find these **logs**? Inside the container I can't find anything. How can I check my auth against the registry is valid? At the moment I use the following environment variables:

```
environment:
      - DOCKER_REGISTRY_URL=https://myregitryurl.de/
      - NO_SSL_VERIFICATION=true
      - ENABLE_DELETE_IMAGES=true
      - BASIC_AUTH_USER=user
      - BASIC_AUTH_PASSWORD=password
```

**Comment by klausmeyer** [comment]
Hi @Nusserdt,

by default my application (when running via the official docker image) is logging everything to `STDOUT` so you should be able to inspect them with the regular docker commands (`docker logs <container-id>`).

As you get the error only on deletion it's likely that the registry itself is rejecting the delete request.
The delete option needs to be enabled as it is turned off by default.

See 🔗 https://docs.docker.com/registry/configuration/#delete

Best, Klaus

**Comment by Nusserdt** [comment]
Hey Klaus,

we found the Log. It is likely that our registry configuration is not correct.

```
I, [2020-11-13T11:49:49.195793 #1]  INFO -- request: DELETE https://myregistry.de/v2/myrepo/manifests/sha256:d1de80cb6586eab553170fe10547cb78a263b59b091397b3dfb15e35946315d3
I, [2020-11-13T11:49:49.195888 #1]  INFO -- request: User-Agent: "Faraday v1.1.0"
Authorization: "Basic dGVzdHsadsGsadsadzdHBhSFASDJk"
I, [2020-11-13T11:49:49.263160 #1]  INFO -- : [3851b84d-bc8c-4792-8eee-4422b85f53f2] Completed 500 Internal Server Error in 275ms (Allocations: 5536)
F, [2020-11-13T11:49:49.264079 #1] FATAL -- : [3851b84d-bc8c-4792-8eee-4422b85f53f2]
[3851b84d-bc8c-4792-8eee-4422b85f53f2] Faraday::ClientError (the server responded with status 405):
[3851b84d-bc8c-4792-8eee-4422b85f53f2]
[3851b84d-bc8c-4792-8eee-4422b85f53f2] app/models/tag.rb:59:in `delete'
[3851b84d-bc8c-4792-8eee-4422b85f53f2] app/controllers/tags_controller.rb:10:in `destroy'
```

Thank you for your support, and as a feedback from my colleagues they like the design of your browser very well. :-)

**Comment by klausmeyer** [comment]
> we found the Log. It is likely that our registry configuration is not correct.

Yes indeed - that's the error the registry throws when the delete is not enabled.

> Thank you for your support, and as a feedback from my colleagues they like the design of your browser very well. :-)

Thanks for the kind words :)
