### ISSUE TITLE
405 error when deleting

### ISSUE THREAD

**Issue by raphaelbernhart** [klausmeyer/docker-registry-browser#364]
I get the following error when deleting via the "Delete Tag..." button.

```
I, [2021-02-05T20:36:10.806437 #1]  INFO -- request: DELETE https://registry.raphaelbernhart.at/v2/thecampers/the-campers.at/manifests/sha256:075fa05fbf351277bf21549c648d02ba247ac311130ddca1ee999fb5a0c706e1
I, [2021-02-05T20:36:10.806506 #1]  INFO -- request: User-Agent: "Faraday v1.3.0"
Authorization: "Basic YWRtaW46TmlnaWdhZG8wMzA0MDI="
I, [2021-02-05T20:36:10.843144 #1]  INFO -- : [0d3eee9fbac547179cff43b4871c0369] Completed 500 Internal Server Error in 164ms (Allocations: 7006)
F, [2021-02-05T20:36:10.844028 #1] FATAL -- : [0d3eee9fbac547179cff43b4871c0369]   
[0d3eee9fbac547179cff43b4871c0369] Faraday::ClientError (**the server responded with status 405**):
[0d3eee9fbac547179cff43b4871c0369]   
[0d3eee9fbac547179cff43b4871c0369] app/models/tag.rb:59:in `delete'
[0d3eee9fbac547179cff43b4871c0369] app/controllers/tags_controller.rb:10:in `destroy'
```

As i researched I found out that the problem lies with the docker-registry side. I have the latest version installed (2.7.1).

So if I use Insomnia I also get the 405 error(https://ec.raphaelbernhart.at/vc3TQT) such as docker-registry api doesn't supports the deletion of image-tags anymore. But in the docs(https://docs.docker.com/registry/spec/api/#deleting-an-image) there isn't described such a deprecation.

Anybody knows the error or had the same error? If yes please let me know.

**Comment by klausmeyer** [comment]
Did you enable the delete feature in the registry?

See: https://docs.docker.com/registry/configuration/#delete
