### ISSUE TITLE
Asks for user/password on localhost

### ISSUE THREAD

**Issue by Clovel** [klausmeyer/docker-registry-browser#369]
I tried running this project on localhost using a Docker container. 

I set the basic auth environment variables for my registry, and as per the logs, authentication succeeded. 

But if I go to localhost:8080, I get a browser pop-up asking for a user and a password. These seem to not be the basic auth credentials for the registry as those do not work. 

Are there any default credentials ?

**Comment by klausmeyer** [comment]
There are no default credentials. When you configure the credentials for your registry you should be able to access the browser interface without any authentication.

Could you please provide more details like some (of course redacted) parts of your exact config and log entries?

**Comment by Clovel** [comment]
Well after some research, the browser pop-up was actually asking me for the registry's credentials. My environment variables weren't set correctly (I had to escape some characters). 

My bad for this non-issue.

**Comment by klausmeyer** [comment]
Ok, perfect. Glad it's working for you.

> My bad for this non-issue.

Not a problem at all :)
