### ISSUE TITLE
collapse namespaces by default

### ISSUE THREAD

**Issue by handfreezer** [klausmeyer/docker-registry-browser#380]
Hello,
   All in title, this is a request because in a private repository with more than 4 or 5 namespace, it is going out of screen, and it is fastidious to scroll down, and worse if there is a lot images by namespace.

Best regards

**Comment by handfreezer** [comment]
Something like this:
https://semantic-ui.com/modules/accordion.html#styled

**Comment by klausmeyer** [comment]
Will have a look when I find some time if it's feasible.

**Comment by klausmeyer** [comment]
Managed to implement something simple.
New config option `COLLAPSE_NAMESPACES` to enable the collapse feature.

Feel free to give it a try:

```shell
$ docker pull klausmeyer/docker-registry-browser:preview-issue-380
$ docker run -e COLLAPSE_NAMESPACES=true klausmeyer/docker-registry-browser:preview-issue-380
```
Let me know what you think about that solution.

**Comment by klausmeyer** [comment]
@handfreezer did you had the chance to have a look?

**Comment by handfreezer** [comment]
Sorry, I just missed your message... I'll have a look on Tuesday at work! Thanks!

**Comment by handfreezer** [comment]
Hello,Sorry for being so late, the visual result is nice, BUT I have a bug : if I deployed images in namespace dir_a/dir_b/dir_c , I'm not able to uncollapse the namespace.
Looking in html code, the div list_group and div collapse contained my images, it seems it is the "down arrow" which is not working.

Little question : may I open an other issue:request to think about a more compact displaying?

**Comment by klausmeyer** [comment]
> Hello,Sorry for being so late [...]

No worries :)

> BUT I have a bug : if I deployed images in namespace dir_a/dir_b/dir_c , I'm not able to uncollapse the namespace.

I've pushed an update which should address the issue with namespaces containing slashes.
Please pull the latest image and give it another try.

I've renamed the config option to `ENABLE_COLLAPSE_NAMESPACES` to align with naming of other options so you'll also need to change that when testing.

> Little question : may I open an other issue:request to think about a more compact displaying?

Sure :)

**Comment by handfreezer** [comment]
Hello,

> I've pushed an update (to the same image-tag) which should address the issue with namespaces containing slashes.
> Please pull the latest image and give it another try.

OK, I'll will make a test next week.

> I've renamed the config option to `ENABLE_COLLAPSE_NAMESPACES` to align with naming of other options so you'll also need to change that when testing.

OK

> > Little question : may I open an other issue:request to think about a more compact displaying?
> 
> Sure :)

Will do

**Comment by handfreezer** [comment]
Hello,

I set this `"ENABLE_COLLAPSE_NAMESPACES=true"` but as I'm using docker_compose, I'm not sure it has updated the image of the container.

In which way may I check this?

**Comment by klausmeyer** [comment]
I haven't used plain docker-compose for a while but if I remember correct it doesn't automatically pull the image when using the same tag. Perhaps a `docker-compose pull` and `docker-compose restart` would already help.

**Comment by handfreezer** [comment]
Sorry for being so long.
It is working!

![image](https://user-images.githubusercontent.com/2912752/121158573-c26d2500-c84a-11eb-8bcc-b27a778ff074.png)

Then:

![image](https://user-images.githubusercontent.com/2912752/121158633-ce58e700-c84a-11eb-8690-fba2eff3eca9.png)

Thanks
