### ISSUE TITLE
Authenticate User Access

### ISSUE THREAD

**Issue by kronik22** [klausmeyer/docker-registry-browser#385]
Feature Request: Add user access authentication, like htpasswd authentication, so that users must use basic authentication to access the docker registry browser website. Enable/Disable a user with DELETE capability and log this information to stdout so that it can be captured by log aggregators like Fluentd. This would be helpful when the ENABLE_DELETE_IMAGES environment variable is set to true, so that there is an audit trail when content is deleted from the registry.

**Comment by klausmeyer** [comment]
Hi and thanks for your request.

The application already supports http-basic and token-auth on the registry/backend.

If I remember correct (as I don't use the features on my own) there should be a browser login-window when there are no credentials configured via ENV (see #135). The audit trail should be available on the registry itself (or the used auth-server - see #112) I guess.

**Comment by kronik22** [comment]
Thank you for the quick response to my feature request. Updating the documentation to note that if Docker Registry basic authentication, htpasswd, is enabled, and the BASIC_AUTH_USER and BASIC_AUTH_PASSWORD environment variables are not set that authentication pass-through is used. This clarification would be helpful.

I really like what you have developed! It's a simple and clean user interface. I deployed it on a Kubernetes cluster to manage our private registry.

If you ever want to create a helm chart let me know. It would be a fun project for me to code.

**Comment by klausmeyer** [comment]
Thanks for the kind words 😀

Agree - I need to invest some time in polishing the documentation.

**Comment by klausmeyer** [comment]
It's now covered in the docs:

https://github.com/klausmeyer/docker-registry-browser/tree/master/docs#authentication
