### ISSUE TITLE
Web UI Login

### ISSUE THREAD

**Issue by gianniskt** [klausmeyer/docker-registry-browser#397]
Hello,

I have a Docker Registry with token authentication, and inserted at the "docker-compose.yml" the TOKEN_AUTH_USER & TOKEN_AUTH_PASSWORD.
Everything works fine and I can browse the UI with the images, but the authentication can only be controlled if we change username & password of the specific user at "docker-compose.yml".
Is there any possibility to add authentication at the UI? 
Another enhancement may be the UI Login and check the user according to User Access List on Docker Authorization Service

**Comment by klausmeyer** [comment]
Hi @gianniskt,

> Is there any possibility to add authentication at the UI?

could you try without providing `TOKEN_AUTH_USER` and `TOKEN_AUTH_PASSWORD`?
This should then lead to the docker-registry-browser to ask the browser for username and password instead.

**Comment by gianniskt** [comment]
> Hi @gianniskt,
> 
> > Is there any possibility to add authentication at the UI?
> 
> could you try without providing `TOKEN_AUTH_USER` and `TOKEN_AUTH_PASSWORD`?
> This should then lead to the docker-registry-browser to ask the browser for username and password instead.
> 
> See 🔗 https://github.com/klausmeyer/docker-registry-browser/tree/master/docs#authentication

Hello, 
Yes i tried that and it's ok. Thank you very much
