### ISSUE TITLE
Can't browse OCI images

### ISSUE THREAD

**Issue by Jean-Daniel** [klausmeyer/docker-registry-browser#409]
When trying to browse an OCI image (default format when pushing from `podman`), the registry fails with error:

```
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI manifest found, but accept header does not support OCI manifests"}]}
```

The registry browser should includes an Accept Header `application/vnd.oci.image.manifest.v1+json`

**Comment by klausmeyer** [comment]
I'll see when I can have a look :)

**Comment by klausmeyer** [comment]
I have something ready to be tested:

```
$ docker run [...] klausmeyer/docker-registry-browser:preview-issue-409
```
@Jean-Daniel Please let me know if it is working for you.

**Comment by klausmeyer** [comment]
@Jean-Daniel Ping

**Comment by Jean-Daniel** [comment]
Sorry, I missed the previous message. I will have a look and tell you if it works.

**Comment by Jean-Daniel** [comment]
It works very well :-) It can now display OCI manifests without error :-)

**Comment by klausmeyer** [comment]
Ok cool 😎 

Will merge the change then so it will be available in `latest` tag soon.
