### ISSUE TITLE
Cannot read *.key file in 1.6.0 docker image

### ISSUE THREAD

**Issue by fLaLaMaster** [klausmeyer/docker-registry-browser#537]
In 1.5.0 seems working. Log:

```
Puma starting in single mode...
* Puma version: 6.0.0 (ruby 3.1.3-p185) ("Sunflower")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 1

/usr/local/bundle/gems/puma-6.0.0/lib/puma/minissl.rb:220:in `check_file': Key file '/certs/auth.key' is not readable (ArgumentError)
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/minissl.rb:290:in `key='
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/minissl/context_builder.rb:39:in `context'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/binder.rb:242:in `block in parse'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/binder.rb:147:in `each'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/binder.rb:147:in `parse'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/runner.rb:164:in `load_and_bind'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/single.rb:44:in `run'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/launcher.rb:186:in `run'
	from /usr/local/bundle/gems/puma-6.0.0/lib/puma/cli.rb:75:in `run'
	from /usr/local/bundle/gems/puma-6.0.0/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:25:in `load'
	from /usr/local/bundle/bin/puma:25:in `<main>'

* Listening on http://0.0.0.0:8080
```

**Comment by klausmeyer** [comment]
Hi @fLaLaMaster,

thanks for reporting.

I remember having SSL related issues with Ruby 3.1.3 (the version used in 1.6.0 release of this app) in another project that have been fixed in Ruby 3.2.0 (the version used in `latest` tag of this app).

Could you please do me a favour and give it a quick try with the `latest` tag?

**Comment by klausmeyer** [comment]
Although it looks more like a general filesystem access issue than SSL related

- https://github.com/puma/puma/blob/v6.0.0/lib/puma/minissl.rb#L220

Anyways - please give it a quick try with the `latest` tag.

**Comment by fLaLaMaster** [comment]
@klausmeyer 
same error : / Forget to say, cert self-signed, created with:

```
openssl req \
  -newkey rsa:4096 -nodes -sha256 -keyout auth.key \
  -addext "subjectAltName = IP:ip_there" \
  -x509 -days 365 -out auth.crt
```

**Comment by klausmeyer** [comment]
I've now tried to reproduce with certs created by the same command.

With different versions:

* `docker run -it --rm -p 8080:8080 -v $PWD/certs:/certs -e SSL_CERT_PATH=/certs/auth.crt -e SSL_KEY_PATH=/certs/auth.key klausmeyer/docker-registry-browser:1.5.0`
* `docker run -it --rm -p 8080:8080 -v $PWD/certs:/certs -e SSL_CERT_PATH=/certs/auth.crt -e SSL_KEY_PATH=/certs/auth.key klausmeyer/docker-registry-browser:1.6.0`
* `docker run -it --rm -p 8080:8080 -v $PWD/certs:/certs -e SSL_CERT_PATH=/certs/auth.crt -e SSL_KEY_PATH=/certs/auth.key klausmeyer/docker-registry-browser:latest`

All are starting up fine with output like this:

```
Puma starting in single mode...
* Puma version: 6.0.0 (ruby 3.1.3-p185) ("Sunflower")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 1
* Listening on http://0.0.0.0:8080
* Listening on ssl://0.0.0.0:8443?cert=%2Fcerts%2Fauth.crt&key=%2Fcerts%2Fauth.key&verify_mode=none
```

Sorry but I really think this must be something in your setup then.

Would suggest to double check permissions on the cert files.
