### ISSUE TITLE
Third page is not loaded

### ISSUE THREAD

**Issue by pm-ur** [klausmeyer/docker-registry-browser#564]
I'm connecting to a registry that has more than 200 repositories. The registry has repositories in multiple namespace levels as shown in example list below:
- a1
- a2
- afolder/repo1
- afolder/repo2
- afolder/subfolder/repo3
- afolder/xrepo
- bfolder/repoX

The web UI displays and groups the namespaces correctly for the first page (first 100 entries) and shows the "Load more..." button. On clicking the button, the page refreshes to show the next 100 entries grouped again by the namespaces within that list. However, I don't see the "Load more..." button on second page.

**Comment by pm-ur** [comment]
Looks like my server doesn't send a 'link' attribute in header for the second page

**Comment by klausmeyer** [comment]
Do you happen to know what kind of registry it is exactly (product / version)?

Is there any other interesting header included on the second page  maybe?

**Comment by pm-ur** [comment]
Unfortunately, it seems like there is no interesting header we could use as an alternative for determining that there are more entries. It could be a bug in the server. The response headers I get are as shown below:
```
< HTTP/2 200
< content-security-policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< content-type: application/json
< date: Thu, 27 Apr 2023 15:22:17 GMT
< docker-distribution-api-version: registry/2.0
< server: Nexus/3.39.0-01 (OSS)
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< content-length: 2001
<
```
