### ISSUE TITLE
no reply to browser when using token authentication via keycloak

### ISSUE THREAD

**Issue by jnsbyr** [klausmeyer/docker-registry-browser#581]
**Setup:** nginx, keycloak, docker registry v2 and docker registry browser as separate docker containers on the same docker host

**Problem description:**

Tried the config shown in https://github.com/klausmeyer/docker-registry-browser/issues/553#issuecomment-1505731097 with the additional environment parameters for the registry browser in a subfolder as described in the [README](https://github.com/klausmeyer/docker-registry-browser/blob/master/docs/README.md#example-nginx-standalone). 
- Token login to registry via keycloak with "docker login" works. 
- Registry browser works if registry auth is disabled. 
- But if registry auth is enabled and the same user is used with environment setting *TOKEN_AUTH_XXXX* the Firefox browser just shows a empty page when opening the registry browser URL because Firefox does not get a response from nginx. Same happens when removing *TOKEN_AUTH_XXXX* settings. Then the user gets prompted for username/password but flow logging and result are the same.

The logs show that the keycloak auth was successful, but I cannot find out where things really go wrong. I would expect the browser to contact the registry again with the token and then respond to Firefox but that does seem not happen. Any help would be much appreciated.

Here is the relevant extract from the journal (slightly redacted). The test was done with the latest registry browser version (1.6.2?) from a few days ago (but previous versions behaved in the same way):

```
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.290962 #1]  INFO -- : [9f2be3de-780d-45c4-822d-15ae21f1d897] Started GET "/browser/" for my-client-IP at 2023-08-06 13:05:19 +0000
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.291626 #1]  INFO -- : [9f2be3de-780d-45c4-822d-15ae21f1d897] Processing by RepositoriesController#index as HTML
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.292515 #1]  INFO -- request: [9f2be3de-780d-45c4-822d-15ae21f1d897] GET https://registry:5000/v2/_catalog?n=100
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.292567 #1]  INFO -- request: [9f2be3de-780d-45c4-822d-15ae21f1d897] User-Agent: "Faraday v1.10.3"
Aug 06 15:05:19 mydockerserver registry[715]: time="2023-08-06T13:05:19.351970191Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.19.9 http.request.host="registry:5000" http.request.id=584fe343-b680-4876-a976-4ba86487830e http.request.method=GET http.request.remoteaddr="my-registry-browser-IP:50740" http.request.uri="/v2/_catalog?n=100" http.request.useragent="Faraday v1.10.3"
Aug 06 15:05:19 mydockerserver registry[715]: my-registry-browser-IP - - [06/Aug/2023:13:05:19 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Faraday v1.10.3"
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.356580 #1]  INFO -- request: [9f2be3de-780d-45c4-822d-15ae21f1d897] GET https://.../protocol/docker-v2/auth?client_id=docker-registry-browser&offline_token=true&scope=registry%3Acatalog%3A%2A&service=docker-registry-mydockerserver
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.356645 #1]  INFO -- request: [9f2be3de-780d-45c4-822d-15ae21f1d897] User-Agent: "Faraday v1.10.3"
Aug 06 15:05:19 mydockerserver registry-browser[715]: Authorization: "Basic <...>"
Aug 06 15:05:19 mydockerserver nginx[715]: my-nginx-IP - my-user-name [06/Aug/2023:13:05:19 +0000] "GET .../protocol/docker-v2/auth?client_id=docker-registry-browser&offline_token=true&scope=registry%3Acatalog%3A%2A&service=docker-registry-mydockerserver HTTP/1.1" 200 956 "-" "Faraday v1.10.3" "-"
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.531898 #1]  INFO -- response: [9f2be3de-780d-45c4-822d-15ae21f1d897] Status 200
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.532069 #1]  INFO -- response: [9f2be3de-780d-45c4-822d-15ae21f1d897] server: "nginx/1.24.0"
Aug 06 15:05:19 mydockerserver registry-browser[715]: set-cookie: "AUTH_SESSION_ID=2d459cd7-7bf1-4bba-88d4-0950dce0e559.e1eecddaa564-2149; Version=1; Path= ... Secure; HttpOnly"
Aug 06 15:05:19 mydockerserver registry-browser[715]: p3p: "CP=\"This is not a P3P policy!\""
Aug 06 15:05:19 mydockerserver registry-browser[715]: x-xss-protection: "1; mode=block"
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.532415 #1]  INFO -- : [9f2be3de-780d-45c4-822d-15ae21f1d897] Redirected to https://my-public-registry.company.com/browser/
Aug 06 15:05:19 mydockerserver registry-browser[715]: I, [2023-08-06T13:05:19.532505 #1]  INFO -- : [9f2be3de-780d-45c4-822d-15ae21f1d897] Completed 302 Found in 241ms (Allocations: 2429)
Aug 06 15:05:19 mydockerserver nginx[715]: my-client-IP - - [06/Aug/2023:13:05:19 +0000] "GET /browser/ HTTP/2.0" 302 95 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" "-"
Aug 06 15:05:19 mydockerserver nginx[715]: my-client-IP - - [06/Aug/2023:13:05:19 +0000] "-" 000 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" "-"
```

**Comment by jnsbyr** [comment]
**Client side:** Using the debugger in the Firefox browser one can see that the browser receives the registry browser session cookie when calling GET on /browser/ and status 302 with a redirect to the original URL /browser/ as shown in the 2nd to last log line above. This triggers another GET of /browser/ with status 0 where nothing is returned to the client, see last log line above.

Cross-Check: When entering or configuring a wrong password the Firefox browser shows the error page "Could not obtain token with configured credentials." from the docker registry browser as it should be.

**Comment by klausmeyer** [comment]
I just tried to reproduce but unfortunately I am not able to.

Could you please provide your configuration (docker compose & nginx config).

**Comment by jnsbyr** [comment]
Thanks for looking into my issue. I have attached the docker and nginx config. Just let me know if anything else is needed.

[docker-compose.yml](https://github.com/klausmeyer/docker-registry-browser/files/12699165/docker-compose.txt)
[nginx.conf](https://github.com/klausmeyer/docker-registry-browser/files/12699170/nginx.txt)

**Comment by klausmeyer** [comment]
Hello @jnsbyr,

your provided examples look good to me - very similar to my setup indeed.

I also had another look at your logs and they look fine except the 000 HTTP status code in the last line as you already mentioned.

The HTTP 000 in nginx logs indicates that the web-browser would have closed the connection in an early stage - before even requesting something.

So I suspect something in the web-browser to be going wrong.

Can you check two things please:

* Are there any errors in the console from your Firefox's dev-tools?
* Are you using any plugins that might interfere?

---

Btw. I updated your initial comment and removed the included `Authorization` header value as it contained some credentials which shouldn't be exposed here. Guess they were logged since you had the [`REGISTRY_LOG_HEADERS`](https://github.com/klausmeyer/docker-registry-browser/tree/master/docs#registry-request-logging) option set.

**Comment by jnsbyr** [comment]
Thanks for fixing my security leak. I tried to obfuscate without confusing the logging, but it seems I missed something.

There is nothing in the dev-tools console of Firefox, regardless which PC I use. The network page just shows 2 HTTP GET to the browser URL, the 2nd with 0 bytes. So I switched to a Chrome where no plugin is installed. Here the console shows a warning:

![grafik](https://github.com/klausmeyer/docker-registry-browser/assets/14251622/42024aea-3a4c-4b89-a0fd-a3719356308c)

Not sure if it is related. Might also be due to my AV program trying to install a Chrome plugin which I had to deny before I was able to enter the URL.

The Chrome network page does not look much different than the Firefox variant, but it is a little more specific regarding the connection status:

![grafik](https://github.com/klausmeyer/docker-registry-browser/assets/14251622/e1dc4fd6-35a0-4167-bbe8-5775d3006948)

The dev-tools show a request header with a session cookie "_docker_registry_browser_session=" for the 2nd aborted GET. This definitely arrived at the web server and was logged, but without a GET. Chrome shows several more canceled transfers, seemingly with the same content and they were also logged by nginx:

[nginx.log](https://github.com/klausmeyer/docker-registry-browser/files/12767505/nginx.txt)

I hope this points into the right direction. If not, please let me know what I should try next. As I'll be on tour for the next 2 weeks please do not close this case due to inactivity on my side, as I will not be able to reply during that time.

**Comment by klausmeyer** [comment]
I would be mostly interested in the first two requests from your screenshot.

* How does the `Set-Cookie` header look like in the first one (Secure & HTTP-Only flags)?
* Anything special in the second one that would explain why it's blocked on some level?

Very interesting are the 3 loaded images after the failed second request as they might be part of an error page chrome tried to show for the second (failed) request.

**Comment by jnsbyr** [comment]
a) 1st request: cookie response

![grafik](https://github.com/klausmeyer/docker-registry-browser/assets/14251622/43b457fa-3c3f-49e5-a587-b8ce432f1702)

Notes: Domain is set to my-public-registry.my-company.com while Partition is set to https://my-company.com. From my point of view the content of Partition is completely unrelated to the authentication process and is possibly supplied by keycloak as aux info.

b) 2nd request: no response

![grafik](https://github.com/klausmeyer/docker-registry-browser/assets/14251622/5eaeddbb-87cb-42cd-a8cb-0f192df8de75)

Can't find anything specific in the dev-tools. Seem to me like there is no response at all the the request just times out.

c) images

![grafik](https://github.com/klausmeyer/docker-registry-browser/assets/14251622/c3485c21-2b0a-4194-81ec-4b64297f862c)

![grafik](https://github.com/klausmeyer/docker-registry-browser/assets/14251622/e9030bf5-e4da-4167-92c2-d7c26c11526a)

The 2nd image is a variant of the 1st image, so I did not include another screenshot.

**Comment by klausmeyer** [comment]
The cookie looks fine as far as I can see.

Perhaps it would be worth a try setting `FORCE_SSL=true` for this application to have it also set the `Secure` flag to avoid having the cookie sent over unencrypted connections.

Otherwise everything looks still like an issue on browser (or networking) side as the request seems to be blocked/cancelled for whatever reason.

I guess I can't help you much further with the issue and will close the issue now.

Feel free to come back to me if you figure out more on your own and there is more indication of a problem on application side.
