### ISSUE TITLE
Running with podman leaves temp files

### ISSUE THREAD

**Issue by Stricken1670** [klausmeyer/docker-registry-browser#650]
Hi there,
I've set up `docker-registry-browser` with the following container file. Works great, apart from the fact that after a reboot it won't start, complaining of two temp files which need to be removed. I've added a work-around service which removes those files before starting up the docker-registry-browser container. Somehow things go too fast during a reboot and those files are not removed.

Feel free to add the `.container` file as an example to the documentation. Makes life real easy.

```
root@graz ~ #  cat /home/docker-registry-browser/.config/containers/systemd/docker-registry-browser.container
[Unit]
Description=Podman docker-registry-browser.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target workaround.service

[Container]
Image=docker.io/klausmeyer/docker-registry-browser
AutoUpdate=registry
Network=host
PublishPort=127.0.0.1:8080:8080
Environment=ADDRESS=127.0.0.1
Environment=PORT=8080
Environment=SECRET_KEY_BASE=7d35a13e4be10475f473a5a62ace286df7662a0c030fc16b19f4e371787bc29ad849516c79b446b55505edf9b9483a175ad8ea6be46257b71b5e450e57db3e02
Environment=ENABLE_COLLAPSE_NAMESPACES=true
Environment=ENABLE_DELETE_IMAGES=true
Environment=RAILS_RELATIVE_URL_ROOT=/browser
Environment=SCRIPT_NAME=/browser

[Service]
Restart=always

[Install]
WantedBy=default.target
```

```
[Unit]
Description=A simple oneshot service

[Service]
Type=oneshot
ExecStart=/bin/rm -rf /home/docker-registry-browser/.local/tmp/storage-run-1000/
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

**Comment by klausmeyer** [comment]
I remember having similar issues like this when the container host system for whatever reason did not do a clean shutdown of the container (e.g. on a hard reboot).

It's very likely related to the `tmp/pid/server.pid` file [used by the puma app-server](https://github.com/klausmeyer/docker-registry-browser/blob/1b66389e53ea60c7cb83900ba56687493a43483a/config/puma.rb#L36).

Do you have any related log entries?

**Comment by klausmeyer** [comment]
Just found this very good article about the topic:

https://ieftimov.com/posts/docker-compose-stray-pids-rails-beyond/

@Stricken1670 Could you maybe try that approach with `tmpfs` and the `PIDFILE` variable?

**Comment by Stricken1670** [comment]
I can't reproduce the issue anymore. I added all your suggestions, didn't help. Took down all suspected config items in my `.zshrc`, didn't help. Restarted it one more time, problem gone. Readded all suspected `.zshrc` items, still worked. Removed all your tmpfs suggestions, it still works.

I'm having _exactly_ the same config as I had before, but now everything works. 

 🤯

**Comment by klausmeyer** [comment]
Ok. Thanks for the feedback.
