### ISSUE TITLE
registry私有仓库使用域名在公网访问必须要ssl，browser配合如何指定ssl呢？

### ISSUE THREAD

**Issue by kk545141** [klausmeyer/docker-registry-browser#656]
registry私有仓库使用域名在公网访问必须要ssl，browser配合如何指定ssl参数呢？

包括crt，key两个文件

**Comment by klausmeyer** [comment]
Sorry but I don't understand Chinese (?) and auto translation might not be correct.

Are you asking how to run the registry browser with public domain name and https?

**Comment by kk545141** [comment]
昨天找到对应参数啦，感谢。
